apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman-app
  name: pacman-deploy2
  namespace: pacman-app
spec:
  clusterSelector:
    matchLabels:
      env: dev
      vendor: OpenShift
