FROM registry.redhat.io/ansible-tower-38/ansible-tower-rhel7:3.8.3

# Rollback to root to allow the pip3 install to succeed
USER 0

#RUN python3 -m ensurepip && pip3 install pysnow certifi kubernetes openshift jq dnspython dig 
#RUN rm -rf /var/lib/awx/venv/ansible && python3 -m venv /var/lib/awx/venv/ansible
ENV PIP_CMD=/var/lib/awx/venv/ansible/bin/pip2.7
#RUN yum install -y bind-utils
#COPY requirements.txt /tmp/requirements.txt
RUN $PIP_CMD install setuptools --upgrade && \
    $PIP_CMD install pysnow certifi dnspython dig && ln -s /var/lib/awx/venv/ansible/bin/dig /usr/bin/dig
    #$PIP_CMD install pysnow certifi dnspython dig jq kubernetes openshift

RUN curl -L -o /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq

#Install the AWS cli
RUN yum install -y unzip && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install

#Install Kubectl cli
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && chmod +x kubectl && \
    mv ./kubectl /usr/bin/kubectl

#Allow PFOlder Permissions
RUN chgrp -R 0 /var/lib && \
    chmod -R ugo+rw /var/lib

USER 1000


dig +noall +short -t A k8s-pacmanap-pacman-826555e08c-321fac9392c47888.elb.us-east-1.amazonaws.com